name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.14'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run format

      - name: Build the project
        run: npm run build
